parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: module

plugins:
  - simple-import-sort

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - prettier/@typescript-eslint

settings:
  react:
    version: detect

rules:
  react/react-in-jsx-scope: "off"
  react/prop-types: "off"
  simple-import-sort/imports: "error"
  sort-imports: "off"

root: true

env:
  node: true
