parser: "@typescript-eslint/parser"

parserOptions:
  project: tsconfig.json
  sourceType: module

plugins:
  - simple-import-sort
  - "@typescript-eslint/eslint-plugin"

extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - prettier
  - prettier/@typescript-eslint

rules:
  simple-import-sort/sort: "error"
  sort-imports: "off"

root: true

env:
  node: true
