apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: flux-system
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/pokernook/graph:0.0.2 # {"$imagepolicy": "flux-system:web"}
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - name: http
              containerPort: 3000
