name: Code Review

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Linters & Formatters
        uses: wearerequired/lint-action@v1.6.0
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: true
          eslint: true
          prettier: true
          eslint_extensions: ts
