name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  publish-container:
    name: Publish Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 15.x

      - name: Install DevSpace
        run: npm install -g devspace

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean CR
        run: doctl registry login --expiry-seconds 600

      - name: Build and Push Container
        run: devspace build --profile production

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 pokernook-k8s

      - name: Deploy to Kubernetes
        run: devspace deploy --skip-build --profile production --wait --timeout 120
