name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  publish-container:
    name: Publish Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean CR
        run: doctl registry login --expiry-seconds 600

      - name: Prepare Container
        id: prepare
        run: |
          URI=registry.digitalocean.com/pokernook/web
          TAG="${URI}:sha-${GITHUB_SHA::8}"
          echo ::set-output name=tag::${TAG}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
          build-args: |
            GRAPHQL_SCHEMA_PATH=https://raw.githubusercontent.com/pokernook/graph/main/schema.graphql
