name: Lint

on:
  push:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x

      - name: Run ESLint script
        run: |
          npm ci
          npm run lint
