name: Lint and Format

on:
  push:

jobs:
  execute-lint-action:
    name: Execute Lint Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - name: Run ESLint, Prettier
        uses: wearerequired/lint-action@v1.7.0
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: true
          eslint: true
          prettier: true
          eslint_extensions: ts
