name: Semantic Analysis

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-codeql:
    name: Run CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: github/codeql-action/init@v1

      - uses: github/codeql-action/analyze@v1
